-- JOIN 연습문제
SELECT *
FROM EMPLOYEES;
SELECT *
FROM DEPARTMENTS;
SELECT *
FROM LOCATIONS;

SELECT '(주)Bit', E.FIRST_NAME || ' ' || E.LAST_NAME AS NAME, E.JOB_ID, D.DEPARTMENT_NAME, L.CITY
FROM EMPLOYEES E,
     DEPARTMENTS D,
     LOCATIONS L
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
  AND D.LOCATION_ID = L.LOCATION_ID
  AND L.CITY = 'Oxford';

SELECT '(주)Bit', E.FIRST_NAME || ' ' || E.LAST_NAME AS NAME, E.JOB_ID, D.DEPARTMENT_NAME, L.CITY
FROM EMPLOYEES E
         JOIN DEPARTMENTS D
              ON (E.DEPARTMENT_ID = D.DEPARTMENT_ID)
         JOIN LOCATIONS L
              ON (D.LOCATION_ID = L.LOCATION_ID)
                  AND L.CITY = 'Oxford';

-- HR 스키마에 있는 Employees, Departments 테이블의 구조를 파악한 후,
-- 사원수가 5명 이상인 부서의 부서명과 사원수를 출력하시오.
-- 이때 사원수가 많은 순으로 정렬하시오.
SELECT D.DEPARTMENT_NAME, COUNT(E.DEPARTMENT_ID)
FROM EMPLOYEES E,
     DEPARTMENTS D
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
GROUP BY D.DEPARTMENT_NAME
HAVING COUNT(E.DEPARTMENT_ID) >= 5
ORDER BY COUNT(*) DESC;

SELECT D.DEPARTMENT_NAME, COUNT(E.DEPARTMENT_ID)
FROM EMPLOYEES E
         JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
GROUP BY D.DEPARTMENT_NAME
HAVING COUNT(E.DEPARTMENT_ID) >= 5
ORDER BY COUNT(*) DESC;

-- 각 사원의 급여에 따른 급여 등급을 보고하려고 한다. 업무별 급여 범위은 JOBS 테이블에 표시된다.
-- 해당 테이블의 구조를 살펴본 후 사원의 성과 이름(Name으로 별칭), 업무ID, 업무명, 부서명, 입사일, 급여를 출력하시오.
SELECT E.FIRST_NAME || ' ' || E.LAST_NAME AS NAME, E.JOB_ID, J.JOB_TITLE, D.DEPARTMENT_NAME, E.HIRE_DATE, E.SALARY
FROM EMPLOYEES E,
     DEPARTMENTS D,
     JOBS J
WHERE E.JOB_ID = J.JOB_ID
  AND E.DEPARTMENT_ID = D.DEPARTMENT_ID
  AND E.SALARY BETWEEN J.MIN_SALARY AND J.MAX_SALARY;

SELECT E.FIRST_NAME || ' ' || E.LAST_NAME AS NAME, E.JOB_ID, J.JOB_TITLE, D.DEPARTMENT_NAME, E.HIRE_DATE, E.SALARY
FROM EMPLOYEES E
         JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
         JOIN JOBS J ON E.JOB_ID = J.JOB_ID
AND E.SALARY BETWEEN J.MIN_SALARY AND J.MAX_SALARY;

-- 각 사원과 직속 상사와의 관계를 이용하여 다음과 같은 형식의 보고서를 작성하고자 한다.
-- 홍길동은 허균에게 보고한다 → Eleni Zlotkey report to Steven King
-- 어떤 사원이 어떤 사원에서 보고하는지를 위 예를 참고하여 출력하시오.
-- 단, 보고할 상사가 없는 사원이 있다면 그 정보도 포함하여 출력하고, 상사의 이름은 대문자로 출력하시오
SELECT E1.FIRST_NAME||' '||E1.LAST_NAME ||' report to '|| E2.FIRST_NAME||' '||E2.LAST_NAME AS "Employees vs Mannager"
FROM EMPLOYEES E1, EMPLOYEES E2
WHERE E1.MANAGER_ID = E2.EMPLOYEE_ID(+);

SELECT E1.FIRST_NAME||' '||E1.LAST_NAME ||' report to '|| E2.FIRST_NAME||' '||E2.LAST_NAME AS "Employees vs Mannager"
FROM EMPLOYEES E1
    LEFT OUTER JOIN EMPLOYEES E2 ON E1.MANAGER_ID = E2.EMPLOYEE_ID;
