-- LISTAGG 함수
-- 그룹에 속해있는 데이터를 가로로 나열할 때 사용한다.

SELECT DEPARTMENT_ID, FIRST_NAME
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID, FIRST_NAME
ORDER BY  DEPARTMENT_ID;
-- 위의 내용을 아래로 변경
SELECT DEPARTMENT_ID,
       LISTAGG(FIRST_NAME, ', ') WITHIN GROUP ( ORDER BY SALARY DESC ) AS FIRST_NAME
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

-- PIVOT 함수
-- 기존 테이블 행을 열로 바꿀 때 사용한다.
-- 부서별,직책별로 그룹화하여 최고 급여 데이터 출력하기
SELECT DEPARTMENT_ID, JOB_ID, MAX(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID, JOB_ID
ORDER BY DEPARTMENT_ID, JOB_ID;
-- PIVOT 으로 변환
SELECT *
FROM (SELECT DEPARTMENT_ID, JOB_ID, SALARY
        FROM EMPLOYEES)
PIVOT(MAX(SALARY)
    FOR DEPARTMENT_ID IN ( 10 AS 부서1, 20 AS 부서2, 30, 40, 50, 60, 70, 80, 90, 100, 110 ))
ORDER BY JOB_ID;

-- UNPIVOT 함수
-- 기존 테이블 열을 행으로 바꿀 때 사용한다.




-- 책 213쪽 5번 문제
SELECT DEPARTMENT_ID, TO_CHAR(HIRE_DATE,'YYYY'),
       COUNT(*) AS CNT, MAX(SALARY) AS MAX_SAL,
       SUM(SALARY) AS SUM_SAL, ROUND(AVG(SALARY),1) AS AVG_SAL
FROM EMPLOYEES
GROUP BY ROLLUP (DEPARTMENT_ID, TO_CHAR(HIRE_DATE,'YYYY'))
ORDER BY DEPARTMENT_ID, TO_CHAR(HIRE_DATE,'YYYY');