-- 테이블 내용을 추가, 수정, 삭제하기 위한 DML


-- 테이블에 새로운 행을 추가하는  INSERT 문
CREATE TABLE DEPT
(
    DEPTNO NUMBER(2),
    DNAME  VARCHAR2(14),
    LOC    VARCHAR2(13)
);

INSERT INTO DEPT(DEPTNO, DNAME, LOC)
VALUES (10, 'ACCOUNTING', 'NEW YORK');

SELECT *
FROM DEPT;

INSERT INTO DEPT
VALUES (20, 'RESEARCH', 'DALLAS');

INSERT INTO DEPT(DEPTNO, DNAME)
VALUES (30, 'SALES');

INSERT INTO DEPT
VALUES (40, 'OPERATIONS', NULL);

INSERT INTO DEPT
VALUES (50, '', 'CHICAGO');

DELETE
FROM DEPT;

ALTER TABLE DEPT
    MODIFY (DEPTNO NUMBER(4), DNAME VARCHAR2(30));

SELECT *
FROM DEPT;

INSERT INTO DEPT
SELECT DEPARTMENT_ID, DEPARTMENT_NAME, LOCATION_ID
FROM DEPARTMENTS;

DROP TABLE TB_CUSTOMER;

SELECT *
FROM TAB;

CREATE TABLE TB_CUSTOMER
(
    CUSTOMER_CD  NUMBER(7),
    CUSTOMER_NM  VARCHAR2(15) NOT NULL,
    MW_FLG       VARCHAR2(1)  NOT NULL,
    BIRTH_DAY    VARCHAR2(8)  NOT NULL,
    PHONE_NUMBER VARCHAR2(13),
    EMAIL        VARCHAR2(30),
    TOTAL_POINT  NUMBER(8)    NOT NULL,
    REG_DTTM     VARCHAR2(14) NOT NULL,
    PRIMARY KEY (CUSTOMER_CD),
    UNIQUE (PHONE_NUMBER),
    UNIQUE (EMAIL)
);

INSERT INTO TB_CUSTOMER
VALUES (2017042, '강원진', 'M', '19810603', '010-8202-8790', 'wjgang@navi.com', 280300,
        TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'));
INSERT INTO TB_CUSTOMER
VALUES (2017053, '나경숙', 'W', '19891225', '010-4509-0043', 'ksna@boram.co.kr', 4500,
        TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'));
INSERT INTO TB_CUSTOMER
VALUES (2017108, '박승대', 'M', '19711230', '', 'sdpark@haso.com', 23450,
        TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'));

SELECT *
FROM TB_CUSTOMER;

-- 테이블의 내용을 수정하기 위한 UPDATE 문
CREATE TABLE EMP
AS
SELECT *
FROM EMPLOYEES;
SELECT *
FROM EMP;

-- 모든 사원의 부서번호를 30번으로 수정한다.
UPDATE EMP
SET DEPARTMENT_ID = 30;

SELECT *
FROM EMP;

-- 모든 사원의 금여를 10% 인상한다.
UPDATE EMP
SET SALARY = SALARY * 1.1;
-- 모든 사원의 입사 을 오늘로 수정한다.
UPDATE EMP
SET HIRE_DATE = SYSDATE;

-- 테이블의 특정 행만 변경


CREATE TABLE EMP
AS
SELECT *
FROM EMPLOYEES;

SELECT *
FROM EMP;

-- 부서번호가 10번인 사원의 부서번호를 30번으로 수정
UPDATE EMP
SET DEPARTMENT_ID = 30
WHERE DEPARTMENT_ID = 10;

-- 급여가 3000 이상인 사원만 급여를 10% 인상
UPDATE EMP
SET SALARY = SALARY * 1.1
WHERE SALARY >= 3000;

-- 2007년에 입사한 사원의 입사일을 오늘로 수정한다.
UPDATE EMP
SET HIRE_DATE = SYSDATE
WHERE SUBSTR(HIRE_DATE, 1, 2) = '07';

CREATE TABLE EMP
AS
SELECT *
FROM EMPLOYEES;

SELECT *
FROM EMPLOYEES;


UPDATE EMPLOYEES
SET DEPARTMENT_ID = 20,
    JOB_ID        = 'FI_MGR'
WHERE FIRST_NAME = 'Susan';

SELECT *
FROM EMP
WHERE LAST_NAME = 'Russell';

UPDATE EMP
SET SALARY         = 17000,
    COMMISSION_PCT = 0.45
WHERE LAST_NAME = 'Russell';

-- 테이블에 불필요한 행(레코드)을 삭제하기 위한 DELETE 문
SELECT *
FROM DEPT;
-- 부서 테이블의 모든 데이터를 삭제한다.
DELETE
FROM DEPT;

DELETE
FROM DEPT
WHERE DEPTNO = 30;

-- DELETE 와 TRUNCATE 의 차이점
-- DELETE는 많은 자원 소모, 삭제 이전 상태로 원상 복귀할 경우를 생각해서 ROLLBACK 정보를 저장하고 있다.
-- TRUNCATE는 DDL 명령문으로 ROLLBACK될 수 없다.

-- MERGE 문
-- MERGE 문은 조건을 비교해서 테이블에 해당 조건에 맞는 데이터가 없으면 INSERT 를, 없으면 UPDATE를 수행하는 문장이다.

SELECT *
FROM TAB;

CREATE TABLE TB_ADD_CUSTOMER
(
    CUSTOMER_CD  VARCHAR2(7) PRIMARY KEY, -- 고객코드
    CUSTOMER_NM  VARCHAR2(10) NOT NULL,   -- 고객명
    MW_FLG       CHAR(1)      NOT NULL,   -- 성별구분
    BIRTH_DAY    VARCHAR2(8)  NOT NULL,   -- 생일
    PHONE_NUMBER VARCHAR2(16)             -- 전화번호
);

INSERT INTO TB_ADD_CUSTOMER(CUSTOMER_CD, CUSTOMER_NM, MW_FLG, BIRTH_DAY, PHONE_NUMBER)
VALUES ('2017108', '박승대', 'M', '19711430', '010-2580-9919');

INSERT INTO TB_ADD_CUSTOMER(CUSTOMER_CD, CUSTOMER_NM, MW_FLG, BIRTH_DAY, PHONE_NUMBER)
VALUES ('2017302', '전미래', 'W', '19740812', '010-8864-0232');

SELECT *
FROM TB_ADD_CUSTOMER;

MERGE INTO TB_CUSTOMER CU
USING TB_ADD_CUSTOMER NC
ON (CU.CUSTOMER_CD = NC.CUSTOMER_CD)
WHEN MATCHED THEN
    UPDATE
    SET CU.CUSTOMER_NM  = NC.CUSTOMER_NM,
        CU.MW_FLG       = NC.MW_FLG,
        CU.BIRTH_DAY    = NC.BIRTH_DAY,
        CU.PHONE_NUMBER = NC.PHONE_NUMBER
WHEN NOT MATCHED THEN
    INSERT (CU.CUSTOMER_CD, CU.CUSTOMER_NM, CU.MW_FLG, CU.BIRTH_DAY, CU.PHONE_NUMBER, CU.EMAIL, CU.TOTAL_POINT,
            CU.REG_DTTM)
    VALUES (NC.CUSTOMER_CD, NC.CUSTOMER_NM, NC.MW_FLG, NC.BIRTH_DAY, NC.PHONE_NUMBER, '', 0,
            TO_CHAR(SYSDATE, 'YYYYMMDDHHMISS'));


-- 문제 EMP01 테이블을 삭제한 후 다음과 같은 구조로 EMP01테이블을 생성하라.
DROP TABLE EMP01;
SELECT *
FROM TAB;

CREATE TABLE EMP01
(
    EMPNO    NUMBER(4)    NOT NULL,
    ENAME    VARCHAR2(10) NOT NULL,
    JOB      VARCHAR2(9),
    MGR      NUMBER(4),
    HIREDATE DATE         NOT NULL,
    SAL      NUMBER(7, 2) NOT NULL,
    COMM     NUMBER(7, 2),
    DEPTNO   NUMBER(2)    NOT NULL
);
SELECT *
FROM TAB;

INSERT INTO EMP01
VALUES (7369, 'SMITH', 'CLEAK', 7836, TO_DATE('1980/12/17', 'YY/MM/DD'), 800, '', 20);
SELECT *
FROM EMP01;

INSERT INTO EMP01
VALUES (7499, 'ALLEN', 'SALESMAN', 7369, TO_DATE('1987/12/20', 'YY/MM/DD'), 1600, 300, 30);


INSERT INTO EMP01
VALUES (7839, 'KING', 'PRESIDENT', '', TO_DATE('1981/02/08', 'YY/MM/DD'), 5000, '', 10);

CREATE TABLE MEMBERS
( NO

);
